In [1]:
import projectors as pr
from importlib import reload
from qiskit import QuantumCircuit, BasicAer
import numpy as np
from scipy.linalg import cossin

In [3]:
reload(pr)

<module 'projectors' from '/Users/lupemacintosh/Documents/Research/quantum-code/projectors.py'>

In [2]:
simulator = BasicAer.get_backend("statevector_simulator")
unitarySim = BasicAer.get_backend("unitary_simulator")

In [5]:
test_circuit = pr.QuantumCircuit(2) 
test_circuit.x([1])
test_circuit.z(1)

test_circuit.cz(0, 1)
test_circuit.cx(1, 0)

test_circuit.cz(0, 1)
#test_circuit.cx(0,1)



"""
test_circuit.h(1)
test_circuit.cx(0, 1)
test_circuit.h(1)"""

#test_circuit.barrier([0, 1])

#test_circuit.measure([0, 1], [0, 1])

test_circuit.draw()

┌───┐   
q_0: ───────────■─┤ X ├─■─
     ┌───┐┌───┐ │ └─┬─┘ │ 
q_1: ┤ X ├┤ Z ├─■───■───■─
     └───┘└───┘

In [6]:
trans_circuit = pr.transpile(test_circuit, unitarySim)
results = unitarySim.run(trans_circuit).result()
unitary = results.get_unitary(trans_circuit)
print("Circuit unitary:\n", np.asarray(unitary).round(5))

Circuit unitary:
 [[0.+0.j 0.+0.j 1.-0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.-0.j]
 [0.+0.j 1.-0.j 0.+0.j 0.+0.j]
 [1.-0.j 0.+0.j 0.+0.j 0.+0.j]]


In [108]:
(compiled_circuit, results) = pr.run_basic_circuit_sv(test_circuit, simulator)
#print(results)

statevector = results.get_statevector(compiled_circuit, 4)
print(statevector)
#percentages = {k: results.get(k) / 1024 for k in ['00', '01', '10', '11']}
#print(percentages)

[0.3821-0.595j 0.3821+0.595j 0.    +0.j    0.    +0.j   ]


In [9]:
Btop = np.array([[0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0]])
u, cs, vdh = cossin(Btop, p=2, q=2)

In [10]:
print(u)
print(cs)
print(vdh)

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.000000e+00  0.000000e+00 -0.000000e+00 -0.000000e+00]
 [ 0.000000e+00  6.123234e-17 -0.000000e+00 -1.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  0.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00  6.123234e-17]]
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0. -1. -0.]]


In [9]:
NOTC = np.array([[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0]])
test = np.matmul(u, np.matmul(cs, vdh))
print(test)

[[ 6.123234e-17  0.000000e+00  1.000000e+00  0.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00  0.000000e+00]
 [ 1.000000e+00  0.000000e+00 -6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]


In [18]:
Bbot = np.array([[0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]])
ub, csb, vdhb = cossin(Bbot, p=2, q=2)

In [19]:
print(ub)
print(csb)
print(vdhb)

[[-1.000000e+00  6.123234e-17  0.000000e+00  0.000000e+00]
 [-6.123234e-17 -1.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00 -1.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00 -0.000000e+00  1.000000e+00]]
[[ 1.000000e+00  0.000000e+00 -0.000000e+00 -0.000000e+00]
 [ 0.000000e+00  6.123234e-17 -0.000000e+00 -1.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  0.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00  6.123234e-17]]
[[ 0. -1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
